### ISSUE TITLE
Trigger build on direct Rust nightly update and update help page

### ISSUE THREAD

**Issue by netvl** [hansjorg/rust-ci#18]
As far as I understand, Rust-CI now tracks Ubuntu PPA for Rust updates. However, for a long time Rust has official nightlies available directly on its web-site, so there is no need to depend on the particular distro. Currently this travis config file seems to be officially suggested (judging by official crates which are now being separated from the compiler tree, e.g. [this one](https://github.com/rust-lang/semver)):

``` yml
install:
  - curl http://www.rust-lang.org/rustup.sh | sudo sh -
script:
  - cargo build --verbose
  - cargo test --verbose
env:
  - LD_LIBRARY_PATH=/usr/local/lib
```

So, I think, it makes sense to migrate Rust-CI to use official nightlies updates and change the documentation on the help page to suggest this configuration instead of Ubuntu-based one.
